### PR TITLE
Added Pytorch3D implementation by facebook

### PR DESCRIPTION
**Pull request by arnabdeypolimi**
# Pull requests instruction

1. Put the bibtex in `awesome-NeRF/citations/<YOUR-PROJECT>.txt`.
2. Modify the README and follow the format TITLE, AUTHOR, CONFERENCE YEAR | OPTIONAL LINK | BIBTEX. For example:
- [NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis](https://www.matthewtancik.com/nerf), Mildenhall et al., ECCV 2020 | [github](https://github.com/bmild/nerf)  | [bibtex](./citations/nerf.txt)

### CODE REVIEW

**Comment by kwea123** [comment]
Good for people working with pytorch3d. Has anyone verified the implementation works correctly?

**Comment by arnabdeypolimi** [comment]
> Good for people working with pytorch3d. Has anyone verified the implementation works correctly?

Yes, I have checked the implementation. It's is working fine

**Comment by yenchenlin** [comment]
Can you just put it in the Pytorch section? Thanks!

**Comment by arnabdeypolimi** [comment]
> Can you just put it in the Pytorch section? Thanks!

done

**Comment by yenchenlin** [comment]
Thank you @arnabdeypolimi !

**Comment by zhangmozhe** [comment]
@arnabdeypolimi  thanks for your check. Did you test the numerical performance for this implementation? Does it match the original NeRF code?

**Pull request merged**
