### PR TITLE
Add 4D Facial Avatars

### PR DESCRIPTION
**Pull request by gafniguy**
Hey, 
Thanks for maintaining this great repo. Would be great if you added 'Dynamic Neural Radiance Fields for Monocular 4D Facial Avatar Reconstruction'

https://arxiv.org/pdf/2012.03065

### CODE REVIEW

**Comment by yenchenlin** [comment]
Done, thank you!

**Comment by gafniguy** [comment]
> Done, thank you!

Hey @yenchenlin , it seems to not appear on the list although the bibtex was updated.

**Comment by yenchenlin** [comment]
Screen Shot 2021-01-08 at 8 00 21 AM
Fix, thanks for letting me know!

**Comment by yenchenlin** [comment]
My bad.

**Pull request closed without merging**
