### PR TITLE
Add NeRF--

### PR DESCRIPTION
**Pull request by mwtarnowski**
[NeRF--: Neural Radiance Fields Without Known Camera Parameters](http://nerfmm.active.vision/)
by  _Zirui Wang_, _Shangzhe Wu_, _Weidi Xie_, _Min Chen_, _Victor Adrian Prisacariu_.

An end-to-end framework for training NeRF models given only RGB images, without pre-computed camera parameters.

### CODE REVIEW

**Comment by kwea123** [comment]
As I observed from a lot of experiments I have conducted with NeRF (on real world car scenes), it is true that NeRF doesn't require any "correct" intrinsics+extrinsics to achieve good results. By "correct" I mean careful camera calibration using checkerboard and so on. Rather, using these correct values, surprisingly, produces **inferior** performance. Hence now I'm always using colmap estimated values even if they are not "correct", and it also seems that there exists a lot of possible intrinsics+extrinsics combinations that make NeRF work well.

This work confirms my experience that many calibrations work for NeRF, and it is possible to learn one of them. I'm looking forward to experimenting how it performs with my data and how much longer it takes compared to NeRF+COLMAP (there are more parameters to optimize, so I expect a longer training time, but at the same time it saves COLMAP time).

**Comment by yenchenlin** [comment]
Hello @mwtarnowski , thanks again!

Same as the previous PR, I have put the citation of this paepr [here](https://github.com/yenchenlin/awesome-NeRF/blob/main/citations/nerf--.txt). Could you update your PR to cite this txt file?

Very helpful and timely PR!

**Comment by yenchenlin** [comment]
@kwea123 Why not colmap init + updating camera parameters during NeRF optimization?

**Comment by mwtarnowski** [comment]
Done.

**Comment by yenchenlin** [comment]
Thank you!

**Comment by kwea123** [comment]
> @kwea123 Why not colmap init + updating camera parameters during NeRF optimization?

Yes, it also improves the score, as shown by the paper. It's something I'd like to implement and test in the future.

**Comment by yenchenlin** [comment]
@kwea123 no problem!

**Pull request merged**
