### PR TITLE
Add a few works and a category of Model Reconstruction

### PR DESCRIPTION
**Pull request by csvt32745**
Works:
- BARF: Bundle-Adjusting Neural Radiance Fields
- Dynamic View Synthesis from Dynamic Monocular Video
- Light Field Networks: Neural Scene Representations with Single-Evaluation Rendering
- NeRF-Tex: Neural Reflectance Field Textures
- Neural Rays for Occlusion-aware Image-based Rendering
- SRF (Stereo Radiance Fields (SRF): Learning View Synthesis from Sparse Views of Novel Scenes)
- ST-NeRF (Editable free-viewpoint video using a layered neural representation)
- UNISURF: Unifying Neural Implicit Surfaces and Radiance Fields for Multi-View Reconstruction
- UORF (Unsupervised Discovery of Object Radiance Fields)

Category:
- Model Reconstruction

### CODE REVIEW

**Comment by csvt32745** [comment]
Update: the bibtex files
I forgot to push them.

**Comment by yenchenlin** [comment]
WOW this is impressive, thank you!

**Comment by yenchenlin** [comment]
Hello @csvt32745 , it's my bad for such a late reply and thank you for the contribution. Do you mind to modify the PR based on my suggestion?

**Comment by csvt32745** [comment]
> Hello @csvt32745 , it's my bad for such a late reply and thank you for the contribution. Do you mind to modify the PR based on my suggestion?

Sure 👍

**Comment by csvt32745** [comment]
Hi~ I've updated the PR based on the latest repository.
Is there any other suggestion I should apply? I didn't see any suggestion in this branch.

**Comment by yenchenlin** [comment]
@csvt32745 I just forgot to check, all good! 

Thanks a lot

**Pull request merged**
