### PR TITLE
Change AutoInt link

### PR DESCRIPTION
**Pull request by kwea123**
change the link of AutoInt from arxiv to its project page

### CODE REVIEW

**Comment by yenchenlin** [comment]
Done, thanks!

**Comment by yenchenlin** [comment]
BTW, @kwea123 have you been able to reproduce this?

**Comment by kwea123** [comment]
Hi, I am currently doing research on dynamic objects training (like the "video" section here), so I probably won't have time to reproduce this.

btw, you closed my pull request but forgot to merge it, could you merge it? Thanks!

**Comment by yenchenlin** [comment]
Got it. Ouch, I fixed it, thanks!

**Pull request merged**
